const menuList = [
    {
        title:'首页',  //菜单标题名称
        key:'/home', //对应的path
        icon:'HomeOutlined',//图标名称
    },
    {
        title:'课程',
        key:'/allCourses',
        icon:'BookOutlined',
        children:[
            {
                title:'全部课程',
                icon:'',
                key:'/allCourses',
            },
            {
                title:'哲学',
                icon:'',
                key:'',
            },
            {
                title:'经济学',
                icon:'',
                key:'',
            },
            {
                title:'法学',
                icon:'',
                key:'',
            },
            {
                title:'教育学',
                icon:'',
                key:'',
            },

            {
                title:'文学',
                icon:'',
                key:'',
            },
            {
                title:'历史学',
                icon:'',
                key:'',
            },
            {
                title:'理学',
                icon:'',
                key:'',
            },
            {
                title:'工学',
                icon:'',
                key:'',
            },
            {
                title:'农学',
                icon:'',
                key:'',
            },
            {
                title:'医学',
                icon:'',
                key:'',
            },
            {
                title:'军事学',
                icon:'',
                key:'',
            },
            {
                title:'管理学',
                icon:'',
                key:'',
            },
            {
                title:'艺术学',
                icon:'',
                key:'',
            },
        ]
    },
    {
        title:'智云课堂',
        key:'',
        icon:'VideoCameraOutlined',
    },
    {
        title:'公开课程',
        key:'',
        icon:'ReadOutlined',
    },
    {
        title:'使用教程',  
        key:'/help',
        icon:'QuestionCircleOutlined',
    },
]
export default menuList